### ISSUE TITLE
Documentation of ExternalConfigurationService

### ISSUE THREAD

**Issue by devstartshop** [lagoshny/ngx-hal-client#19]
What is a proper way to set the root URL in a generic way when the angular app is part of the same WAR file as spring data rest backend.

I dont want to hardcode the hostname, in this file or take it from a variable in environment.ts

I tried using below:
**Not working**
```
  getRootUri(): string {
    return window.location.origin +'/';
  }
```

**Working fine**
```
  getRootUri(): string {
    return 'https://myapp.devstartshop.com/';
  }
```

**Here is the full file**

```typescript
import {Injectable} from '@angular/core';
import {ExternalConfiguration, ExternalConfigurationHandlerInterface} from '@lagoshny/ngx-hal-client';
import {HttpClient} from '@angular/common/http';

@Injectable()
export class ExternalConfigurationService implements ExternalConfigurationHandlerInterface {

  constructor(private http: HttpClient) {
  }

  getProxyUri(): string {
    return '/spring-data/api/';
  }

  getRootUri(): string {
    return window.location.origin +'/';
  }

  getHttp(): HttpClient {
    return this.http;
  }

  getExternalConfiguration(): ExternalConfiguration {
    return null;
  }

  setExternalConfiguration(externalConfiguration: ExternalConfiguration) {
  }

  deserialize(): any {
  }

  serialize(): any {
  }
}

```

**Comment by lagoshny** [comment]
Do you mean you have backend and frontend on the same host? And you can't get this host to make request to backend?

I think that it's not problem with hal-client, you need to have a look like JS allows you to get current host and pass it to hal-client configuration.

Unfortunately, I have not experience to deploy backend and frontend within same WAR. 
If you want you can provide some simple app in github to demonstrate how you to do it. 
And I will see what I can offer you to resolve your problem.

**Comment by lagoshny** [comment]
I close this issue if you will have any questions reopen it.
