### ISSUE TITLE
getall as page

### ISSUE THREAD

**Issue by simonebracaloni** [lagoshny/ngx-hal-client#21]
Would it be possible to get a ResourcePage using the getAll  method? What is the recommended way to do so? 
I would like to avoid to send a searchPage request without a query, but I may be wrong on that.

**Comment by poljvd** [comment]
I also would like to have a ResourcePage as a result for getAll(). At the moment I have added the following function to the REST service of my application:

```
  public getAllPage(options?: HalOptions, subType?: SubTypeBuilder): Observable<ResourcePage<MyResource>> {
    var hack = this as any; // get access to some private variables of super...
    return hack.resourceService.getAll(MyResource, hack.resource, hack.embedded, options, subType).pipe(
            mergeMap((resourceArray: ResourceArray<MyResource>) => {
                return observableOf(new ResourcePage<MyResource>(resourceArray));
            })
        );
  }
```

It would ofcourse be nice if something similar can be added to the library.

**Comment by lagoshny** [comment]
Hi all! 
I will see what I can do within few days, thanks

**Comment by lagoshny** [comment]
@simonebracaloni , @poljvd I added **getAllPage** method to the library, you can found it in **1.0.24** version that already available in npm.

**Comment by poljvd** [comment]
Thank you!
