### ISSUE TITLE
How to remove the dependency on CommonJS or AMD dependencies?

### ISSUE THREAD

**Issue by grrenier** [lagoshny/ngx-hal-client#31]
Hello, is there a way to remove the dependency on CommonJS or AMD?

> Warning: \node_modules\@lagoshny\ngx-hal-client\fesm2015\lagoshny-ngx-hal-client.js depends on 'uri-templates'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

> Warning: \node_modules\@lagoshny\ngx-hal-client\fesm2015\lagoshny-ngx-hal-client.js depends on 'hash.js'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by lagoshny** [comment]
Hi @grrenier , can you try a new `1.1.7 version` warnings should be gone.

If you will have some warnings please add more information about your application build system and angular version.

**Comment by grrenier** [comment]
Hi @lagoshny , I migrated to the new version 1.1.7 but I still have the warnings. By the way, you are doing a great job on this package, it makes the job easier.

**Comment by lagoshny** [comment]
@grrenier can you tell which Angular version do you use? Do you use Angular CLI to build a project?

**Comment by grrenier** [comment]
Hi @lagoshny , I'm using Angular 11.1.2 and Angular CLI 11.1.4

**Comment by lagoshny** [comment]
Hi @grrenier, thank you for the information.

I have published a new version where I changed CommonJS dependencies to es2015.
Try to build your project with the **1.1.9** version to check the warnings.

**Comment by grrenier** [comment]
I updated to the new version and there are no warning. Thank you for the fix. 

I have a question: How do we do the PUT, POST or PATCH of a many to many relationship replacing the objects in the JSON with URLs? If you prefer I can move this comment to another place to keep this issue clean.

**Comment by lagoshny** [comment]
Yes, it will be better to move the question about many many relationships to another issue.
I created new [issue ](https://github.com/lagoshny/ngx-hal-client/issues/39) for this question.
