### ISSUE TITLE
Creating a new Resource fails

### ISSUE THREAD

**Issue by poljvd** [lagoshny/ngx-hal-client#36]
I updated to v1.1.7 and creating a new resource now fails due to a incorrect URL. I checked and v1.1.6 is working correctly.

I have a repository with the name 'rule' and creating a resource gives me the following error:
```HTTP Error HttpErrorResponse {headers: HttpHeaders, status: 403, statusText: "Forbidden", url: "http://localhost:4200/api/reporules", ok: false, …}```

In short: A slash is missing from the URL as it should be ```http://localhost:4200/api/repo/rules```.

**Comment by lagoshny** [comment]
Hi @poljvd, thank you for the issue. I fixed it in **v1.1.8** that had been published.
