### ISSUE TITLE
The resource is not being created correctly after calling the `page()` or `size()` function of a `ResourcePage<T>`

### ISSUE THREAD

**Issue by grrenier** [lagoshny/ngx-hal-client#41]
Hello @lagoshny , suppose I have the following Employee resource with an extra getter for the `fullName` that is not in the REST API model and I need to implement a pagination by calling the `searchPage()` function of the employee REST service.
```
export class Employee extends Resource {
    id: number;
    firstName: string;
    lastName: string;
    constructor(){
       super();
    }
    get fullName() :string {
        return this.firstName + '  ' + this.lastName;
    }
}
```
The first call works as expected, I'm able to get the resources and they have the fullName property.

But when the page size or the page index change I call the `page()` or the `size()` function on the `ResourcePage` object then the resources I'm getting don't have the extra getter `fullName`, it seams like the real constructor of the Employee class is not being called to create the Employee resource.
Thank you

**Comment by lagoshny** [comment]
Hi @grrenier, thank you for the issue. I fixed it in a new version **v1.2.1** try to update to this version and check it.
