### ISSUE TITLE
ResourcePage: The page should be set to 1 when the page size changes

### ISSUE THREAD

**Issue by grrenier** [lagoshny/ngx-hal-client#43]
Hello @lagoshny , I found this issue, suppose I have 60 resources and I'm using the pagination, when I'm in the 3th page with a page size of 20 and I change the page size to 100 then the page index should be set to 1 to be able to see the data.
Thank you

**Comment by lagoshny** [comment]
Hi @grrenier , thank you for the issue. Fixed it in **1.2.2** version.
