### ISSUE TITLE
ERESOLVE unable to resolve dependency tree when running npm install

### ISSUE THREAD

**Issue by cypressious** [lagoshny/ngx-hal-client#47]
When running `npm` install, I'm getting the following error in my project:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: arcus@undefined
npm ERR! Found: @angular/common@11.2.11
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"11.2.11" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^4.0.0" from @lagoshny/ngx-hal-client@1.2.3
npm ERR! node_modules/@lagoshny/ngx-hal-client
npm ERR!   @lagoshny/ngx-hal-client@"1.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Is there anything that can be done about this?

**Comment by lagoshny** [comment]
Hi @cypressious , try to clear npm cache and rerun npm install. If the error will be again add full npm logs and your project's package.json dependencies.

**Comment by cypressious** [comment]
@lagoshny I've created an empty Angular project using `ng new` at https://github.com/cypressious/hal-client-npm-issue. Then I've tried running `npm install @lagoshny/ngx-hal-client --save` and got the same error.

Here's the log: [2021-04-29T11_13_43_119Z-debug.log](https://github.com/lagoshny/ngx-hal-client/files/6398114/2021-04-29T11_13_43_119Z-debug.log)

**Comment by lagoshny** [comment]
@cypressious, It seems that you are using the latest nodejs version with npm v7.10.0. It is not stable release and I think that can has some bugs [npm issue](https://github.com/npm/cli/issues/2339). Try to install the latest LTS nodejs version 14.16.1 and try again.
