### ISSUE TITLE
Enable Ivy in Angular compiler options

### ISSUE THREAD

**Issue by grrenier** [lagoshny/ngx-hal-client#48]
Hello @lagoshny, 
Is there a way to enable Ivy in Angular compiler options? With Ivy enabled I know there is an error when we pass a type as a parameter to be able to create an object of that generic type, for example:

`createObject(type: {new(): T;})`

or the equivalent using arrow functions

`createObject(type: new() => T)`

Do you know how to solve this issue?

Thank you

**Comment by lagoshny** [comment]
Hi @grrenier , can you provide some example? 

For angular libs it is recommend is not enable Ivy see more [here](https://angular.io/guide/creating-libraries#publishing-your-library). If you will use Ivy in your project then all libs also will be compiled with Ivy too.

**Comment by grrenier** [comment]
Hi @lagoshny, 
I didn't provide you an example because the issue was related to dependency injection issue on my side. 
Thank you
