### ISSUE TITLE
Old peer dependencies in package.json

### ISSUE THREAD

**Issue by MartinKutz** [lagoshny/ngx-hal-client#49]
If you have installed the ngx-hal-client and then run "npm ls --production", you get an error, that the peer dependency of this lib is missing:
```
npm ERR! peer dep missing: @angular/common@^4.0.0, required by @lagoshny/ngx-hal-client@1.2.3
npm ERR! peer dep missing: @angular/core@^4.0.0, required by @lagoshny/ngx-hal-client@1.2.3
```

I have installed Angular 10.2.0.
The dependencies are configured here within the package.json:

https://github.com/lagoshny/ngx-hal-client/blob/5d8ae4aa6080e88d14bd9c98125424600868e770/projects/ngx-hal-client/package.json#L9

https://github.com/lagoshny/ngx-hal-client/blob/5d8ae4aa6080e88d14bd9c98125424600868e770/projects/ngx-hal-client/package.json#L10

Can you please update this section?  Maybe it's something possible like ">=" instead of "^".

Thanks & Best regards,
Martin

**Comment by lagoshny** [comment]
Hi @MartinKutz , thank you for the issue. I changed peer dependencies in **1.2.4** version that already published. Try this version.

**Comment by MartinKutz** [comment]
Wow, thank you for your very fast reaction. Version 1.2.4 fixes the problem.
Best regards,
Martin
