### ISSUE TITLE
Better Templated URI support

### ISSUE THREAD

**Issue by designerkamal** [lagoshny/ngx-hal-client#8]
Support for various other types for templatedURIs [(RFC6570) compliant](https://tools.ietf.org/html/rfc6570)

for e.g the following are also valid URI-Templates, currently not working with ngx-hal-client
http://example.com/dictionary/{word} 
http://example.com/artists/{artist} 

[uri-templates](https://www.npmjs.com/package/uri-templates) can be used in the *Relation methods to replace LinkParams

**Comment by lagoshny** [comment]
@designerkamal, thanks for you suggestion I will add support to other URI template urls soon.
